filepath: examples/bvh/custom_avatar_animations/right_hand_on_head.bvh
start_frame_idx: 1
end_frame_idx: 175
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftThigh
    - RightThigh
scale: 0.005
up: +y
